CREATE TABLE `payroll_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payrollReturnId` int NOT NULL,
	`employeeId` int NOT NULL,
	`alertType` enum('Pending','Overdue','Reminder') NOT NULL,
	`alertMessage` text NOT NULL,
	`severity` enum('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
	`status` enum('Active','Acknowledged','Resolved','Dismissed') NOT NULL DEFAULT 'Active',
	`acknowledgedBy` int,
	`acknowledgedAt` timestamp,
	`resolvedAt` timestamp,
	`notifiedUsers` text,
	`notificationSent` boolean DEFAULT false,
	`notificationSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payroll_details` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payrollRunId` int NOT NULL,
	`employeeId` int NOT NULL,
	`basicSalary` decimal(10,2) NOT NULL,
	`housingAllowance` decimal(10,2) DEFAULT '0',
	`transportAllowance` decimal(10,2) DEFAULT '0',
	`foodAllowance` decimal(10,2) DEFAULT '0',
	`otherAllowances` decimal(10,2) DEFAULT '0',
	`overtimePay` decimal(10,2) DEFAULT '0',
	`bonus` decimal(10,2) DEFAULT '0',
	`grossSalary` decimal(10,2) NOT NULL,
	`taxDeduction` decimal(10,2) DEFAULT '0',
	`socialInsurance` decimal(10,2) DEFAULT '0',
	`healthInsurance` decimal(10,2) DEFAULT '0',
	`pensionContribution` decimal(10,2) DEFAULT '0',
	`loanDeduction` decimal(10,2) DEFAULT '0',
	`advanceDeduction` decimal(10,2) DEFAULT '0',
	`otherDeductions` decimal(10,2) DEFAULT '0',
	`totalDeductions` decimal(10,2) NOT NULL,
	`netSalary` decimal(10,2) NOT NULL,
	`governmentRegisteredAmount` decimal(10,2) NOT NULL,
	`complianceAdjustment` decimal(10,2) DEFAULT '0',
	`returnAmount` decimal(10,2) DEFAULT '0',
	`bankTransferAmount` decimal(10,2) NOT NULL,
	`finalNetPayroll` decimal(10,2) NOT NULL,
	`bankName` varchar(100),
	`accountNumber` varchar(50),
	`bankTransferReference` varchar(100),
	`transferDate` timestamp,
	`status` enum('Pending','Paid','Cancelled') NOT NULL DEFAULT 'Pending',
	`paymentMethod` enum('Bank Transfer','Cash','Cheque') NOT NULL DEFAULT 'Bank Transfer',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_details_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payroll_returns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payrollDetailId` int NOT NULL,
	`employeeId` int NOT NULL,
	`payrollRunId` int NOT NULL,
	`returnAmount` decimal(10,2) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`returnStatus` enum('Pending','Completed','Overdue','Waived') NOT NULL DEFAULT 'Pending',
	`returnedAmount` decimal(10,2) DEFAULT '0',
	`returnDate` timestamp,
	`returnMethod` enum('Bank Transfer','Cash','Salary Deduction') DEFAULT 'Bank Transfer',
	`returnReference` varchar(100),
	`recordedBy` int,
	`verifiedBy` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_returns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payroll_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodMonth` int NOT NULL,
	`periodYear` int NOT NULL,
	`runDate` timestamp NOT NULL DEFAULT (now()),
	`status` enum('Draft','Processing','Completed','Cancelled') NOT NULL DEFAULT 'Draft',
	`totalEmployees` int DEFAULT 0,
	`totalGrossSalary` decimal(15,2) DEFAULT '0',
	`totalDeductions` decimal(15,2) DEFAULT '0',
	`totalNetSalary` decimal(15,2) DEFAULT '0',
	`totalBankTransfer` decimal(15,2) DEFAULT '0',
	`totalReturnAmount` decimal(15,2) DEFAULT '0',
	`processedBy` int,
	`approvedBy` int,
	`approvedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salary_components` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`basicSalary` decimal(10,2) NOT NULL,
	`housingAllowance` decimal(10,2) DEFAULT '0',
	`transportAllowance` decimal(10,2) DEFAULT '0',
	`foodAllowance` decimal(10,2) DEFAULT '0',
	`otherAllowances` decimal(10,2) DEFAULT '0',
	`governmentRegisteredAmount` decimal(10,2) NOT NULL,
	`taxPercentage` decimal(5,2) DEFAULT '0',
	`socialInsurancePercentage` decimal(5,2) DEFAULT '0',
	`healthInsurancePercentage` decimal(5,2) DEFAULT '0',
	`pensionPercentage` decimal(5,2) DEFAULT '0',
	`bankName` varchar(100),
	`accountNumber` varchar(50),
	`iban` varchar(50),
	`isActive` boolean NOT NULL DEFAULT true,
	`effectiveFrom` timestamp NOT NULL DEFAULT (now()),
	`effectiveTo` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `salary_components_id` PRIMARY KEY(`id`)
);
