import { useState, useEffect } from 'react';
import { Download, Eye, FileText } from 'lucide-react';
import { selfServiceApi, Payslip } from '../services/selfServiceApi';
import { EmptyState } from '../components/common/EmptyState';
import { toast } from 'sonner';

export default function MyPayslipsPage() {
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadPayslips();
  }, []);

  const loadPayslips = async () => {
    try {
      setLoading(true);
      const data = await selfServiceApi.getAllPayslips();
      setPayslips(data);
    } catch (error) {
      console.error('Failed to load payslips:', error);
      toast.error('Failed to load payslips');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (payslip: Payslip) => {
    try {
      await selfServiceApi.downloadPayslip(payslip.id);
      toast.success(`Downloading payslip for ${payslip.month}`);
    } catch (error) {
      console.error('Failed to download payslip:', error);
      toast.error('Failed to download payslip');
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-foreground">My Payslips</h1>
        <p className="text-muted-foreground mt-1">View and download your salary payslips</p>
      </div>

      {/* Payslips List */}
      {payslips.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No payslips available"
          description="Your payslips will appear here once they are generated by the payroll department"
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {payslips.map(payslip => (
            <div
              key={payslip.id}
              className="bg-card border border-border rounded-xl p-6 hover:border-primary/30 transition-all"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="p-3 bg-primary/10 rounded-lg">
                  <FileText className="w-6 h-6 text-primary" />
                </div>
                <span className="text-xs text-muted-foreground">{payslip.id}</span>
              </div>

              <div className="space-y-3">
                <div>
                  <h3 className="font-semibold text-foreground text-lg">{payslip.month}</h3>
                </div>

                <div className="space-y-2 py-3 border-y border-border">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Gross Salary:</span>
                    <span className="font-medium text-foreground">
                      ${payslip.grossSalary.toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Deductions:</span>
                    <span className="font-medium text-red-500">
                      -${payslip.deductions.toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between text-base pt-2 border-t border-border">
                    <span className="font-semibold text-foreground">Net Salary:</span>
                    <span className="font-bold text-primary">
                      ${payslip.netSalary.toLocaleString()}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-2 pt-2">
                  <button
                    onClick={() => window.open(payslip.downloadUrl, '_blank')}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-muted hover:bg-muted/70 rounded-lg transition-colors text-sm font-medium text-foreground"
                  >
                    <Eye className="w-4 h-4" />
                    View
                  </button>
                  <button
                    onClick={() => handleDownload(payslip)}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg transition-colors text-sm font-medium"
                  >
                    <Download className="w-4 h-4" />
                    Download
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Info Box */}
      {payslips.length > 0 && (
        <div className="bg-primary/10 border border-primary/20 rounded-xl p-4">
          <p className="text-sm text-foreground">
            <span className="font-semibold">Note:</span> Payslips are generated on the last working day of each month. 
            If you notice any discrepancies, please submit a "Payslip Inquiry" request through the Self Service portal.
          </p>
        </div>
      )}
    </div>
  );
}
